#!/usr/bin/env bash
# This Bash script displays 'To infinity and beyond' indefinitely
# Requirement: In between each iteration of the looperation  add a sleep 2

while true
do
    echo "To infinity and beyond"
    sleep 2
done
