#!/usr/bin/env bash
# A script that displays Best School 10 times using while and displays hi at the 9th iteration

num=1

while [ $num -le 10 ]
do
    echo "Best School"
    if [ $num -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
