#!/usr/bin/env bash
# A script that displays Best School 10 times using while and displays hi at the 9th iteration

n=1

while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n -eq 9 ]
    then
        echo "Hi"
    fi
    ((n++))
done
